name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  google_sign_in: ^6.0.2

  flutter_svg: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/frame_1171275436.jpeg
  - assets/images/image_266.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_129_x2.svg
  - assets/vectors/search_118_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/subtract_29_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_252.jpeg
  - assets/images/frame_1171275439.jpeg
  - assets/vectors/search_15_x2.svg
  - assets/vectors/user_15_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/subtract_23_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_137_x2.svg
  - assets/vectors/image_2_x2.svg
  - assets/vectors/subtract_6_x2.svg
  - assets/vectors/search_113_x2.svg
  - assets/images/image_256.png
  - assets/images/image_21.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/search_17_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/user_110_x2.svg
  - assets/vectors/subtract_9_x2.svg
  - assets/images/image_191.png
  - assets/images/image_255.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_130_x2.svg
  - assets/vectors/subtract_7_x2.svg
  - assets/vectors/search_141_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_191.png
  - assets/images/image_28.png
  - assets/images/image_271.png
  - assets/images/image_282.png
  - assets/images/image_29.png
  - assets/images/image_253.png
  - assets/vectors/subtract_2_x2.svg
  - assets/vectors/user_121_x2.svg
  - assets/vectors/search_140_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/frame_1171275442.jpeg
  - assets/images/image_258.png
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/subtract_35_x2.svg
  - assets/vectors/user_126_x2.svg
  - assets/vectors/search_117_x2.svg
  - assets/images/image_259.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/frame_1171275435.png
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/user_136_x2.svg
  - assets/vectors/search_13_x2.svg
  - assets/vectors/subtract_36_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_7.png
  - assets/images/image_17.png
  - assets/vectors/user_113_x2.svg
  - assets/vectors/subtract_33_x2.svg
  - assets/vectors/search_138_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/subtract_1_x2.svg
  - assets/vectors/user_143_x2.svg
  - assets/vectors/search_116_x2.svg
  - assets/images/bookpad_high_resolution_logo_white_transparent_2.png
  - assets/vectors/super_g_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_19.png
  - assets/images/image_251.png
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/subtract_13_x2.svg
  - assets/vectors/user_19_x2.svg
  - assets/vectors/search_11_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_1.png
  - assets/images/image_17.png
  - assets/vectors/subtract_20_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/search_124_x2.svg
  - assets/vectors/user_12_x2.svg
  - assets/images/rectangle_828043.png
  - assets/images/image_3.png
  - assets/images/image_1.png
  - assets/images/image_4.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_5.png
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/subtract_39_x2.svg
  - assets/vectors/search_125_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_969_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_968_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/user_114_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_963_x2.svg
  - assets/vectors/vector_966_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_962_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_21.png
  - assets/images/image_20.png
  - assets/images/image_23.png
  - assets/images/image_24.png
  - assets/images/image_19.png
  - assets/images/image_22.png
  - assets/vectors/user_141_x2.svg
  - assets/vectors/search_120_x2.svg
  - assets/vectors/subtract_32_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_30.png
  - assets/images/image_29.png
  - assets/vectors/search_12_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/subtract_15_x2.svg
  - assets/vectors/user_138_x2.svg
  - assets/images/image_267.jpeg
  - assets/images/frame_1171275441.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_13_x2.svg
  - assets/vectors/search_19_x2.svg
  - assets/vectors/subtract_27_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/images/image_17.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_4.png
  - assets/vectors/search_16_x2.svg
  - assets/vectors/subtract_26_x2.svg
  - assets/vectors/user_140_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/images/image_17.png
  - assets/images/image_3.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/search_1_x2.svg
  - assets/vectors/subtract_10_x2.svg
  - assets/vectors/user_133_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_127_x2.svg
  - assets/vectors/subtract_x2.svg
  - assets/vectors/search_132_x2.svg
  - assets/images/image_5.png
  - assets/images/image_3.png
  - assets/images/image_4.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_1.png
  - assets/images/rectangle_828043.png
  - assets/vectors/vector_964_x2.svg
  - assets/vectors/vector_961_x2.svg
  - assets/vectors/vector_967_x2.svg
  - assets/vectors/frame_36550_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/user_131_x2.svg
  - assets/vectors/search_126_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/subtract_8_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_965_x2.svg
  - assets/vectors/file_download_x2.svg
  - assets/vectors/file_download_1_x2.svg
  - assets/vectors/frame_36549_x2.svg
  - assets/vectors/file_download_2_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/images/image_24.png
  - assets/images/image_268.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/search_111_x2.svg
  - assets/vectors/user_120_x2.svg
  - assets/vectors/subtract_11_x2.svg
  - assets/images/frame_1171275436.jpeg
  - assets/images/frame_1171275437.jpeg
  - assets/images/frame_1171275440.jpeg
  - assets/images/frame_11712754351.jpeg
  - assets/images/frame_1171275438.jpeg
  - assets/images/frame_1171275439.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/subtract_43_x2.svg
  - assets/vectors/user_125_x2.svg
  - assets/vectors/search_119_x2.svg
  - assets/images/image_2510.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/frame_11712754351.jpeg
  - assets/vectors/subtract_17_x2.svg
  - assets/vectors/user_135_x2.svg
  - assets/vectors/search_121_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_261.jpeg
  - assets/images/frame_1171275437.jpeg
  - assets/vectors/subtract_38_x2.svg
  - assets/vectors/search_137_x2.svg
  - assets/vectors/user_11_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/images/image_264.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/frame_11712754361.jpeg
  - assets/vectors/subtract_25_x2.svg
  - assets/vectors/user_16_x2.svg
  - assets/vectors/search_139_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/ellipse_37.jpeg
  - assets/vectors/user_119_x2.svg
  - assets/vectors/subtract_22_x2.svg
  - assets/vectors/ellipse_371_x2.svg
  - assets/vectors/edit_021_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/edit_02_x2.svg
  - assets/vectors/search_142_x2.svg
  - assets/vectors/view_off_x2.svg
  - assets/vectors/circle_lock_012_x2.svg
  - assets/images/frontpage.jpeg
  - assets/images/bookpad_high_resolution_logo_white_transparent_2.png
  - assets/images/image_262.png
  - assets/images/image_22.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/subtract_24_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/search_134_x2.svg
  - assets/vectors/user_17_x2.svg
  - assets/images/image_291.png
  - assets/images/image_282.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/subtract_5_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/search_133_x2.svg
  - assets/vectors/user_116_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_17.png
  - assets/images/image_6.png
  - assets/vectors/user_14_x2.svg
  - assets/vectors/subtract_42_x2.svg
  - assets/vectors/search_128_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_17.png
  - assets/images/image_5.png
  - assets/vectors/user_117_x2.svg
  - assets/vectors/search_114_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/subtract_18_x2.svg
  - assets/images/button_primary_1.png
  - assets/images/button_primary.jpeg
  - assets/images/button_primary_4.jpeg
  - assets/images/button_primary_3.png
  - assets/images/button_primary_2.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_122_x2.svg
  - assets/vectors/subtract_3_x2.svg
  - assets/vectors/search_131_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/search_14_x2.svg
  - assets/vectors/circle_lock_011_x2.svg
  - assets/vectors/view_off_1_x2.svg
  - assets/vectors/user_112_x2.svg
  - assets/vectors/view_off_2_x2.svg
  - assets/vectors/circle_lock_01_x2.svg
  - assets/vectors/xmlid_28_x2.svg
  - assets/vectors/subtract_40_x2.svg
  - assets/images/frame_1171275444.jpeg
  - assets/images/frame_1171275443.jpeg
  - assets/images/frame_1171275441.jpeg
  - assets/images/frame_1171275442.jpeg
  - assets/images/frame_11712754361.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/frame_1171275435.png
  - assets/vectors/search_129_x2.svg
  - assets/vectors/subtract_34_x2.svg
  - assets/vectors/user_123_x2.svg
  - assets/images/image_7.png
  - assets/images/image_5.png
  - assets/images/image_3.png
  - assets/images/image_1.png
  - assets/images/image_4.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_6.png
  - assets/vectors/subtract_37_x2.svg
  - assets/vectors/search_110_x2.svg
  - assets/vectors/user_115_x2.svg
  - assets/images/image_20.png
  - assets/images/image_265.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_139_x2.svg
  - assets/vectors/search_143_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/subtract_21_x2.svg
  - assets/images/frame_1171275440.jpeg
  - assets/images/image_26.jpeg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_118_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/subtract_12_x2.svg
  - assets/vectors/search_123_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_28.png
  - assets/images/image_257.png
  - assets/vectors/user_134_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/search_136_x2.svg
  - assets/vectors/subtract_41_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_271.png
  - assets/images/image_281.png
  - assets/vectors/user_132_x2.svg
  - assets/vectors/subtract_30_x2.svg
  - assets/vectors/search_130_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/frame_1171275438.jpeg
  - assets/images/image_261.jpeg
  - assets/vectors/subtract_19_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/search_135_x2.svg
  - assets/vectors/user_111_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_254.jpeg
  - assets/images/frame_1171275443.jpeg
  - assets/vectors/subtract_16_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/user_142_x2.svg
  - assets/vectors/search_122_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/frame_1171275444.jpeg
  - assets/images/image_263.jpeg
  - assets/vectors/search_18_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/user_124_x2.svg
  - assets/vectors/subtract_28_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/subtract_14_x2.svg
  - assets/vectors/user_128_x2.svg
  - assets/vectors/search_127_x2.svg
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/images/image_25.png
  - assets/images/image_23.png
  - assets/vectors/user_18_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/subtract_4_x2.svg
  - assets/vectors/search_115_x2.svg
  - assets/images/image_253.png
  - assets/images/image_27.png
  - assets/images/bookpad_high_resolution_logo_black_1_photoroom_png_photoroom_3.png
  - assets/vectors/user_1_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/subtract_31_x2.svg
  - assets/vectors/search_112_x2.svg

